global:
  scrape_interval:     15s
  evaluation_interval: 15s
  scrape_timeout:      10s

  external_labels:
    environment: 'development'
    app:         'lunaris'

scrape_configs:

  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']


  - job_name: 'lunaris_backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']
    relabel_configs:
      - target_label: service
        replacement:  'lunaris-backend'


  - job_name: 'lunaris_worker'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['worker:9091']
    relabel_configs:
      - target_label: service
        replacement:  'lunaris-worker'
